---
title: "README"
output: html_document
---


This project is the requirement towards the completion of the Practical Machine Learning course of Data Science Track.



Project Goals:-

-The goal of your project is to predict the manner in which the exercise was done.



Dataset Description :-

The training data for this project are available here: 

https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv

The test data are available here: 

https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv

A full description is available at the site where the data was obtained:


<http://groupware.les.inf.puc-rio.br/har>

Abstract: Human Activity Recognition - HAR - has emerged as a key research area in the last years and is gaining increasing attention by the pervasive computing research community, especially for the development of context-aware systems. There are many potential applications for HAR, like: elderly monitoring, life log systems for monitoring energy expenditure and for supporting weight-loss programs, and digital assistants for weight lifting exercises.


This human activity recognition research has traditionally focused on discriminating between different activities, i.e. to predict "which" activity was performed at a specific point in time (like with the Daily Living Activities dataset above). The approach proposed for the Weight Lifting Exercises dataset is to investigate "how (well)" an activity was performed by the wearer. The "how (well)" investigation has only received little attention so far, even though it potentially provides useful information for a large variety of applications,such as sports training.

Using devices such as Jawbone Up, Nike FuelBand, and Fitbit it is now possible to collect a large amount of data about personal activity relatively inexpensively. These type of devices are part of the quantified self movement - a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it. In this project, your goal will be to use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants. They were asked to perform barbell lifts correctly and incorrectly in 5 different ways.



Project requirements:-
1) Load and Clean the data , as many observation in dataset contains NAs and blank 
2) split the data into training and validation sets. 
3) Centering and scaling was done to normalise the data, using training datset and applied to validation dataset as well
4) Training control paramters were selected as below:-
method = "repeatedcv", number = 3,repeats = 1)

5) Neural network, K Nearest Neighbours, Suppotr Vector machine using svmRadialCost and Random forest Machine learning techniques were used.
6) Variable importance helped in final selection of predictors of predictors 
7) All the models were combined by majority voting criteria
8) Accuracy was compared between individual modes and combined model
9) random forest turned out to be best
10) Finally test data was used to 



Packages to be installed :-
(caret) 
(kernlab)
(plyr)
(dplyr)
(car)
(MASS)
(ggplot2)
(corrgram)
(MASS)
(reshape)
(scales)


Running the script:-

save the dataset in your working directory and run the script by typing source("pml.R.R") in the R studio console.
